<a href="https://colab.research.google.com/github/geroalbornoz/markets/blob/master/BS_rava_scrapper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
#Usando BS para scrapear data. Ejemplo con la Main Page de Rava.com
#tuto de YT: https://www.youtube.com/watch?v=Cb_5A6geOUw&t=575s
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [94]:
lista_especies = []
lista_ultimo = []
lista_dia = []
lista_mes = []
lista_a√±o = []

In [95]:
URL = "http://www.rava.com/"
page = requests.get(URL)
soup = BeautifulSoup(page.text, "html.parser")
especies = soup.find_all("tr", attrs={"class": "ci"})
movimientos = soup.find_all("td", attrs={"class": "c1"})

In [96]:
# soup

In [97]:
especies

[<tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DOLAR OFICIAL">DOLAR OFICIAL</a></td>
 <td class="c1">84,25</td>
 <td class="c1 cg">0</td>
 <td class="c1 cg">0,9</td>
 <td class="c1 cg">33,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DOLAR SOLIDARIO">DOLAR SOLIDARIO</a></td>
 <td class="c1">139,01</td>
 <td class="c1 cg">0</td>
 <td class="c1 cg">0,9</td>
 <td class="c1 cg">69,8</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DOLAR CCL">DOLAR CCL</a></td>
 <td class="c1">149,88</td>
 <td class="c1 cg">2,0</td>
 <td class="c1 cg">1,5</td>
 <td class="c1 cg">101,4</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=RIESGO PAIS">RIESGO PAIS</a></td>
 <td class="c1">1.391</td>
 <td class="c1 cg">-0,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=LELIQ">LELIQ</a></td>
 <td class="c1">36,00</td>
 <td class="c1 cg">0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=MERVAL">MERVAL</a></td>
 <td class="c1">48.223</td>
 <td class="c1 cr">-0,6</td>
 <td class="c1 cg">6,5</td>
 <td class="c1 cg">15,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=BBAR">BBAR</a></td>
 <td class="c1">141,000</td>
 <td class="c1 cr">-2,0</td>
 <td class="c1 cg">12,4</td>
 <td class="c1 cg">0,4</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=BYMA">BYMA</a></td>
 <td class="c1">548,000</td>
 <td class="c1 cr">-1,5</td>
 <td class="c1 cg">4,6</td>
 <td class="c1 cg">70,5</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=COME">COME</a></td>
 <td class="c1">2,620</td>
 <td class="c1 cg">0,4</td>
 <td class="c1 cg">10,1</td>
 <td class="c1 cg">47,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=CVH">CVH</a></td>
 <td class="c1">413,000</td>
 <td class="c1 cg">0,9</td>
 <td class="c1 cg">7,4</td>
 <td class="c1 cg">35,4</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GGAL">GGAL</a></td>
 <td class="c1">114,250</td>
 <td class="c1 cr">-0,7</td>
 <td class="c1 cg">18,5</td>
 <td class="c1 cr">-6,0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=PAMP">PAMP</a></td>
 <td class="c1">78,700</td>
 <td class="c1 cg">3,6</td>
 <td class="c1 cg">7,7</td>
 <td class="c1 cg">58,0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=TECO2">TECO2</a></td>
 <td class="c1">205,000</td>
 <td class="c1 cg">0,1</td>
 <td class="c1 cg">4,5</td>
 <td class="c1 cg">20,0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=TGSU2">TGSU2</a></td>
 <td class="c1">159,800</td>
 <td class="c1 cg">2,1</td>
 <td class="c1 cg">4,5</td>
 <td class="c1 cg">47,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=TXAR">TXAR</a></td>
 <td class="c1">54,800</td>
 <td class="c1 cr">-0,9</td>
 <td class="c1 cr">-5,4</td>
 <td class="c1 cg">113,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=YPFD">YPFD</a></td>
 <td class="c1">552,000</td>
 <td class="c1 cr">-3,3</td>
 <td class="c1 cg">8,2</td>
 <td class="c1 cr">-35,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=AGRO">AGRO</a></td>
 <td class="c1">18,150</td>
 <td class="c1 cg">0,3</td>
 <td class="c1 cg">7,7</td>
 <td class="c1 cg">93,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=BHIP">BHIP</a></td>
 <td class="c1">10,050</td>
 <td class="c1 cg">0</td>
 <td class="c1 cg">8,6</td>
 <td class="c1 cr">-28,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=BPAT">BPAT</a></td>
 <td class="c1">66,100</td>
 <td class="c1 cr">-3,4</td>
 <td class="c1 cg">4,1</td>
 <td class="c1 cg">51,3</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=CADO">CADO</a></td>
 <td class="c1">23,800</td>
 <td class="c1 cg">2,6</td>
 <td class="c1 cg">3,5</td>
 <td class="c1 cg">19,0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=CARC">CARC</a></td>
 <td class="c1">2,690</td>
 <td class="c1 cr">-0,4</td>
 <td class="c1 cg">1,5</td>
 <td class="c1 cg">92,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=CELU">CELU</a></td>
 <td class="c1">22,000</td>
 <td class="c1 cr">-2,9</td>
 <td class="c1 cg">4,8</td>
 <td class="c1 cr">-10,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=CTIO">CTIO</a></td>
 <td class="c1">105,000</td>
 <td class="c1 cr">-1,4</td>
 <td class="c1 cg">1,9</td>
 <td class="c1 cg">50,0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DYCA">DYCA</a></td>
 <td class="c1">-</td>
 <td class="c1 cg">-</td>
 <td class="c1 cg">6,1</td>
 <td class="c1 cg">31,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=EDSH">EDSH</a></td>
 <td class="c1">-</td>
 <td class="c1 cg">-</td>
 <td class="c1 cg">-</td>
 <td class="c1 cg">-</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=FERR">FERR</a></td>
 <td class="c1">8,450</td>
 <td class="c1 cr">-0,6</td>
 <td class="c1 cr">-1,7</td>
 <td class="c1 cg">9,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GAMI">GAMI</a></td>
 <td class="c1">174,500</td>
 <td class="c1 cg">0,6</td>
 <td class="c1 cg">0,3</td>
 <td class="c1 cg">100,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GBAN">GBAN</a></td>
 <td class="c1">-</td>
 <td class="c1 cg">-</td>
 <td class="c1 cg">2,6</td>
 <td class="c1 cr">-2,5</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GRIM">GRIM</a></td>
 <td class="c1">-</td>
 <td class="c1 cg">-</td>
 <td class="c1 cr">-2,9</td>
 <td class="c1 cr">-15,8</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=HAVA">HAVA</a></td>
 <td class="c1">137,000</td>
 <td class="c1 cg">0</td>
 <td class="c1 cg">0,7</td>
 <td class="c1 cr">-7,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=INVJ">INVJ</a></td>
 <td class="c1">17,000</td>
 <td class="c1 cg">0,3</td>
 <td class="c1 cg">3,3</td>
 <td class="c1 cg">58,9</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=IRSA">IRSA</a></td>
 <td class="c1">58,800</td>
 <td class="c1 cg">2,1</td>
 <td class="c1 cg">5,5</td>
 <td class="c1 cg">15,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=LOMA">LOMA</a></td>
 <td class="c1">139,800</td>
 <td class="c1 cr">-2,2</td>
 <td class="c1 cg">4,3</td>
 <td class="c1 cg">16,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=METR">METR</a></td>
 <td class="c1">19,150</td>
 <td class="c1 cg">2,4</td>
 <td class="c1 cg">0,3</td>
 <td class="c1 cg">18,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=MOLI">MOLI</a></td>
 <td class="c1">90,900</td>
 <td class="c1 cg">1,0</td>
 <td class="c1 cg">1,8</td>
 <td class="c1 cg">57,8</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=OEST">OEST</a></td>
 <td class="c1">22,300</td>
 <td class="c1 cr">-0,5</td>
 <td class="c1 cg">2,1</td>
 <td class="c1 cr">-23,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=PGR">PGR</a></td>
 <td class="c1">11,000</td>
 <td class="c1 cr">-0,5</td>
 <td class="c1 cg">1,4</td>
 <td class="c1 cr">-39,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=RICH">RICH</a></td>
 <td class="c1">106,750</td>
 <td class="c1 cr">-0,9</td>
 <td class="c1 cg">4,4</td>
 <td class="c1 cr">-8,0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=ROSE">ROSE</a></td>
 <td class="c1">10,500</td>
 <td class="c1 cg">1,9</td>
 <td class="c1 cr">-0,9</td>
 <td class="c1 cg">87,5</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=SEMI">SEMI</a></td>
 <td class="c1">5,800</td>
 <td class="c1 cg">0,9</td>
 <td class="c1 cg">9,4</td>
 <td class="c1 cg">79,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=PAMP">PAMP</a></td>
 <td class="c1">78,700</td>
 <td class="c1 cg">3,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GCLA">GCLA</a></td>
 <td class="c1">34,800</td>
 <td class="c1 cg">3,0</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=METR">METR</a></td>
 <td class="c1">19,150</td>
 <td class="c1 cg">2,4</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GBAN">GBAN</a></td>
 <td class="c1">-</td>
 <td class="c1 cg">-</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GRIM">GRIM</a></td>
 <td class="c1">-</td>
 <td class="c1 cg">-</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DYCA">DYCA</a></td>
 <td class="c1">-</td>
 <td class="c1 cg">-</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DIA">DIA</a></td>
 <td align="left" class="movil_hide_cell"><b></b>Dow Jones (ETF)</td>
 <td class="c1">283,470</td>
 <td class="c1 cr">-0,2</td>
 <td class="c1 cg">7,0</td>
 <td class="c1 cr">-0,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=SPY">SPY</a></td>
 <td align="left" class="movil_hide_cell">S&amp;P 500 (ETF)</td>
 <td class="c1">350,560</td>
 <td class="c1 cg">0,1</td>
 <td class="c1 cg">7,4</td>
 <td class="c1 cg">8,9</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=EWZ">EWZ</a></td>
 <td align="left" class="movil_hide_cell">Brasil (ETF)</td>
 <td class="c1">30,310</td>
 <td class="c1 cg">1,4</td>
 <td class="c1 cg">12,8</td>
 <td class="c1 cr">-36,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=FXE">FXE</a></td>
 <td align="left" class="movil_hide_cell">Euro (ETF)</td>
 <td class="c1">111,720</td>
 <td class="c1 cg">0,5</td>
 <td class="c1 cg">2,0</td>
 <td class="c1 cg">5,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=USO">USO</a></td>
 <td align="left" class="movil_hide_cell">Petr√≥leo (ETF)</td>
 <td class="c1">26,410</td>
 <td class="c1 cr">-2,8</td>
 <td class="c1 cg">4,6</td>
 <td class="c1 cr">-74,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=XLF">XLF</a></td>
 <td align="left" class="movil_hide_cell">Servicios Financieros (ETF)</td>
 <td class="c1">25,000</td>
 <td class="c1 cr">-0,7</td>
 <td class="c1 cg">4,8</td>
 <td class="c1 cr">-18,8</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=XLV">XLV</a></td>
 <td align="left" class="movil_hide_cell">Salud (ETF)</td>
 <td class="c1">110,500</td>
 <td class="c1 cg">0,6</td>
 <td class="c1 cg">8,7</td>
 <td class="c1 cg">8,5</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=AMZN">AMZN</a></td>
 <td align="left" class="movil_hide_cell">Amazon.com Inc.</td>
 <td class="c1">3.313</td>
 <td class="c1 cr">-0,3</td>
 <td class="c1 cg">9,1</td>
 <td class="c1 cg">79,3</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=BAC">BAC</a></td>
 <td align="left" class="movil_hide_cell">Bank of America Corporation</td>
 <td class="c1">24,460</td>
 <td class="c1 cr">-0,6</td>
 <td class="c1 cg">3,2</td>
 <td class="c1 cr">-30,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DIS">DIS</a></td>
 <td align="left" class="movil_hide_cell">Walt Disney Co.</td>
 <td class="c1">126,980</td>
 <td class="c1 cg">0,0</td>
 <td class="c1 cg">4,7</td>
 <td class="c1 cr">-12,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=HD">HD</a></td>
 <td align="left" class="movil_hide_cell">Home Depot Inc.</td>
 <td class="c1">283,620</td>
 <td class="c1 cr">-0,8</td>
 <td class="c1 cg">6,3</td>
 <td class="c1 cg">29,9</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=MSFT">MSFT</a></td>
 <td align="left" class="movil_hide_cell">Microsoft Corp.</td>
 <td class="c1">223,240</td>
 <td class="c1 cr">0,0</td>
 <td class="c1 cg">10,3</td>
 <td class="c1 cg">41,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=AAPL">AAPL</a></td>
 <td align="left" class="movil_hide_cell">Apple Computer Inc.</td>
 <td class="c1">119,060</td>
 <td class="c1 cg">0,2</td>
 <td class="c1 cg">9,4</td>
 <td class="c1 cg">62,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=AXP">AXP</a></td>
 <td align="left" class="movil_hide_cell">American Express Co.</td>
 <td class="c1">96,630</td>
 <td class="c1 cr">-1,5</td>
 <td class="c1 cg">5,9</td>
 <td class="c1 cr">-22,4</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=CAT">CAT</a></td>
 <td align="left" class="movil_hide_cell">Caterpillar Inc.</td>
 <td class="c1">161,940</td>
 <td class="c1 cr">-0,8</td>
 <td class="c1 cg">3,1</td>
 <td class="c1 cg">9,7</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=CSCO">CSCO</a></td>
 <td align="left" class="movil_hide_cell">Cisco Systems Inc.</td>
 <td class="c1">37,260</td>
 <td class="c1 cg">0,1</td>
 <td class="c1 cg">3,8</td>
 <td class="c1 cr">-22,3</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DIS">DIS</a></td>
 <td align="left" class="movil_hide_cell">Walt Disney Co.</td>
 <td class="c1">126,980</td>
 <td class="c1 cg">0,0</td>
 <td class="c1 cg">4,7</td>
 <td class="c1 cr">-12,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=GS">GS</a></td>
 <td align="left" class="movil_hide_cell">The Goldman Sachs Group, Inc.</td>
 <td class="c1">200,990</td>
 <td class="c1 cr">-1,0</td>
 <td class="c1 cg">6,3</td>
 <td class="c1 cr">-12,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=HON">HON</a></td>
 <td align="left" class="movil_hide_cell">Honeywell International Inc.</td>
 <td class="c1">184,970</td>
 <td class="c1 cg">0,8</td>
 <td class="c1 cg">12,1</td>
 <td class="c1 cg">4,5</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=INTC">INTC</a></td>
 <td align="left" class="movil_hide_cell">Intel Corporation  </td>
 <td class="c1">45,270</td>
 <td class="c1 cr">-0,9</td>
 <td class="c1 cg">2,2</td>
 <td class="c1 cr">-24,4</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=JPM">JPM</a></td>
 <td align="left" class="movil_hide_cell">JP Morgan Chase &amp; Co.</td>
 <td class="c1">103,300</td>
 <td class="c1 cr">-1,0</td>
 <td class="c1 cg">5,4</td>
 <td class="c1 cr">-25,9</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=MCD">MCD</a></td>
 <td align="left" class="movil_hide_cell">McDonald's Corporation</td>
 <td class="c1">216,610</td>
 <td class="c1 cg">0,1</td>
 <td class="c1 cg">1,7</td>
 <td class="c1 cg">9,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=MRK">MRK</a></td>
 <td align="left" class="movil_hide_cell">Merck &amp; Co. Inc.</td>
 <td class="c1">80,850</td>
 <td class="c1 cg">0,5</td>
 <td class="c1 cg">7,5</td>
 <td class="c1 cr">-11,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=NKE">NKE</a></td>
 <td align="left" class="movil_hide_cell">Nike Inc.</td>
 <td class="c1">128,810</td>
 <td class="c1 cr">-0,8</td>
 <td class="c1 cg">7,3</td>
 <td class="c1 cg">27,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=TRV">TRV</a></td>
 <td align="left" class="movil_hide_cell">The Travelers Companies, Inc.</td>
 <td class="c1">127,170</td>
 <td class="c1 cr">-0,3</td>
 <td class="c1 cg">5,4</td>
 <td class="c1 cr">-7,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=V">V</a></td>
 <td align="left" class="movil_hide_cell">Visa Inc.</td>
 <td class="c1">199,350</td>
 <td class="c1 cg">0,9</td>
 <td class="c1 cg">9,7</td>
 <td class="c1 cg">6,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=WBA">WBA</a></td>
 <td align="left" class="movil_hide_cell">Walgreens Boots Alliance, Inc.</td>
 <td class="c1">37,410</td>
 <td class="c1 cr">-0,3</td>
 <td class="c1 cg">9,9</td>
 <td class="c1 cr">-36,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DIA">DIA</a></td>
 <td align="left" class="movil_hide_cell"><b></b>Dow Jones (ETF)</td>
 <td class="c1">283,470</td>
 <td class="c1 cr">-0,2</td>
 <td class="c1 cg">7,0</td>
 <td class="c1 cr">-0,6</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=SPY">SPY</a></td>
 <td align="left" class="movil_hide_cell">S&amp;P 500 (ETF)</td>
 <td class="c1">350,560</td>
 <td class="c1 cg">0,1</td>
 <td class="c1 cg">7,4</td>
 <td class="c1 cg">8,9</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=EWZ">EWZ</a></td>
 <td align="left" class="movil_hide_cell">Brasil (ETF)</td>
 <td class="c1">30,310</td>
 <td class="c1 cg">1,4</td>
 <td class="c1 cg">12,8</td>
 <td class="c1 cr">-36,1</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=USO">USO</a></td>
 <td align="left" class="movil_hide_cell">Petr√≥leo (ETF)</td>
 <td class="c1">26,410</td>
 <td class="c1 cr">-2,8</td>
 <td class="c1 cg">4,6</td>
 <td class="c1 cr">-74,2</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=SLV">SLV</a></td>
 <td align="left" class="movil_hide_cell">Plata (ETF)</td>
 <td class="c1">23,760</td>
 <td class="c1 cg">0,6</td>
 <td class="c1 cg">8,1</td>
 <td class="c1 cg">42,5</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=DBB">DBB</a></td>
 <td align="left" class="movil_hide_cell">Aluminio, cobre, zinc (ETF)</td>
 <td class="c1">16,110</td>
 <td class="c1 cg">0,8</td>
 <td class="c1 cg">3,3</td>
 <td class="c1 cg">7,8</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=XLE">XLE</a></td>
 <td align="left" class="movil_hide_cell">Energia (Pond. Petroleras) (ETF)</td>
 <td class="c1">28,940</td>
 <td class="c1 cr">-2,1</td>
 <td class="c1 cg">0,8</td>
 <td class="c1 cr">-51,8</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=XLI">XLI</a></td>
 <td align="left" class="movil_hide_cell">Industrial (ETF)</td>
 <td class="c1">81,150</td>
 <td class="c1 cr">-0,1</td>
 <td class="c1 cg">7,0</td>
 <td class="c1 cr">-0,4</td>
 </tr>, <tr class="ci">
 <td align="left" class="c1 b"><a href="/empresas/perfil.php?e=XLV">XLV</a></td>
 <td align="left" class="movil_hide_cell">Salud (ETF)</td>
 <td class="c1">110,500</td>
 <td class="c1 cg">0,6</td>
 <td class="c1 cg">8,7</td>
 <td class="c1 cg">8,5</td>

In [98]:
#loops

for i in especies :
  row = i.find_all("td")
  lista_especies.append(row[0].text.strip()) #Ticker
  lista_ultimo.append(row[1].text.strip()) #Ultimo
  lista_dia.append(row[2].text.strip()) #dia

In [99]:
# lista_ultimo

In [ ]:
lista_especies

In [101]:
#Crear el df
data = pd.DataFrame()
data["especie"] = lista_especies
data["ultimo"] = lista_ultimo
data["dia"] = lista_dia
data = data[data["especie"] != ""]

data

             especie   ultimo     dia
0      DOLAR OFICIAL    84,25       0
1    DOLAR SOLIDARIO   139,01       0
2          DOLAR CCL   149,88     2,0
3        RIESGO PAIS    1.391    -0,6
4              LELIQ    36,00       0
..               ...      ...     ...
139          DOSep21  129,000  -8,000
140          DOOct21  134,000       -
141          MVDIC20        -       -
142          I.RFX20   63.242     3,3
143       RFX20Mar21   73.100    -3,3

[144 rows x 3 columns]

In [102]:
data.to_excel("Cotizaciones Rava.xlsx")